---
kind: pipeline
type: docker
name: default

workspace:
  path: /src

steps:
- name: install-dependencies
  image: gmetrixr/baseimage:node-18-dev-v1
  commands:
# Substitution: parameter//substring/replacemenet. So "// \/ / -" means replace / with -
  - echo "The image tag is ${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}"
  - sudo chown -R node .
  - pnpm install

- name: lint-and-build
  image: gmetrixr/baseimage:node-18-dev-v1
  commands:
  - pnpm lint
  - pnpm check
  - pnpm test
  - pnpm build

#Commits all modified files. npm publish doesn't work with unstaged changes
- name: npm-prepare-main
  image: gmetrixr/baseimage:node-18-dev-v1
  when:
    branch: [main]
    event:
      exclude: [pull_request]
  commands:
  - |
    /bin/sh -c 'git add -A; #Needed for git diff-index pick up new files
      if git diff-index --quiet HEAD; 
      then #Run if no difference (exit code 0)
        echo "No changes to commit"; 
      else #Run if there is a difference difference (exit code 1)
        git commit -am "Publish related changes. [CI SKIP]"; 
      fi'
  - export N=`node -p require\(\'./package.json\'\).name` && echo $N
  - "pnpm version patch --message \"v%s: $N [CI SKIP]\""
  - git push origin ${DRONE_BRANCH}
  - git push --tags origin ${DRONE_BRANCH}

- name: npm-publish-main
  image: gmetrixr/baseimage:node-18-dev-v1
  when:
    branch: [main]
    event:
      exclude: [pull_request]
  environment:
    REGISTRY_TOKEN:
      from_secret: npm_token
  commands:
    - npm set registry https://registry.npmjs.org/
    - npm set //registry.npmjs.org/:_authToken $REGISTRY_TOKEN
    - npm publish

# - name: on-conflict-main
#   image: gmetrixr/baseimage:node-18-dev-v1
#   when:
#     branch: [main]
#     status: [failure]
#     event:
#       exclude: [pull_request]
#   commands:
#   - git push origin ${DRONE_BRANCH}
#   - git merge origin/${DRONE_BRANCH}
#   - export N=`node -p require\(\'./package.json\'\).name` && echo $N
#   - pnpm version patch --no-git-tag-version
#   - "git commit -am \"trigger: $N [no skip]\""
#   - git push origin ${DRONE_BRANCH}
#   - git push --tags origin ${DRONE_BRANCH}

trigger:
  branch: [main]
  event: [push, pull_request]
